### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Freyert** [benbria/node-bunyan-lumberjack#2]
Before I can use this wonderful work you've done I need you to add a [LICENSE](http://choosealicense.com/).

Do you have plans to add one?

**Comment by jwalton** [comment]
Oops.  My apologies; I'm usually pretty careful about that.  I'll add an
MIT license when I'm next near a computer.

**Comment by jwalton** [comment]
Enjoy!

**Comment by Freyert** [comment]
@jwalton you're an officer and a gentleman. Thank you for building this up and sharing it out!
![salute](http://www.reactiongifs.com/r/slte.gif)
